### ISSUE TITLE
Project Update 1

### ISSUE THREAD

**Issue by brucknerp** [brucknerp/jpn_gen_pop#1]
This week we chose a topic, chose a text, and set up our repo and the [project board](https://github.com/brucknerp/jpn_gen_pop/projects/1). 

We had trouble because knew we wanted to look at gender differences in speech patterns over time in Japanese, but didn't know what text would show speech patterns. We ultimately decided on song lyrics from different decades. 

In the upcoming week we plan to finalize our chosen texts and determine how we will approach document analysis and data collection.

**Comment by Idi0teque** [comment]
This sounds really interesting! I wonder, are you going to be including artificial Vocaloid artists written by opposite-gender writers, and analyzing those? Although honestly any song written and performed by people of differing genders seem like they might pose interesting questions.

**Comment by richiebful** [comment]
Beyond looking at the gender of songwriters, it would be interesting to see what features ya'll are going to look at. I'm not very familiar how gender is represented in Japanese language, but it would be interesting to look at subject-object and pronoun usage like in the Russian folk tales project.

**Comment by mtm80** [comment]
When you decided on this topic, did you have any sort of a theory about the outcome of this research or is this purely exploratory?  I'm just curious about the starting point of the project.   Are you testing any theory or just exploring?

**Comment by ianloughney** [comment]
This project looks incredibly interesting. I'm not particularly knowledgeable in Japanese, is it a language with grammatical gender, and if so is that something you intend to look at in your analysis? If I can also offer a suggestion, it might not hurt to send an email to Professor Abdesalam Soudi in the linguistics department if you ever need help here, he's a sociolinguist and language and gender is one of his areas of study specifically.

**Comment by brucknerp** [comment]
@Idi0teque No, unfortunately, haha. There is just not enough time to incorporate virtual artists--but that would definitely be something to look at. But we are looking to keep track of whether the songwriter and singer are of the same gender or not, because this can of course skew things.

@richiebful It's mostly sentence-final endings, Chinese character compounds, and pronoun choice (like Russian?), but look forward to it!

@mtm80 My fan theory is that the stereotypical speech endings for women are falling out of use in more recent years, and this project was born out of a conversation with some of my native Japanese-speaker friends on the topic.

@ianloughney There is no grammatical gender! Which makes this more interesting, IMO.
