### ISSUE TITLE
configure web site

### ISSUE THREAD

**Issue by djbpitt** [brucknerp/jpn_gen_pop#3]
- [x] Create  project group on obdurodon and add all team members and instructors
- [x] Create group-writable setgid directory space on obdurodon with owner
- [x] Create virtual host on obdurodon
- [x] Create "obdurodon" subdirectory for web site files in repo, with dummy index.xhtml file, and upload the file to obdurodon
- [x] Update projects.txt file in course admin folder
- [x] Notify project team and instructors

**Comment by djbpitt** [comment]
Impeded because it requires information about the short name of the project and the owner

**Comment by amk231** [comment]
@djbpitt 
Gina will be the project owner and use jpop in their URL.

**Comment by djbpitt** [comment]
The site has been created. Access it in a browser at http://jpop.obdurodon.org.
